### ISSUE TITLE
Layout improvements for better readability and clarity

### ISSUE THREAD

**Issue by KimJBaran** [ialbert/biostar-central#140]
The current BioStar layout is functionally sound, but some font/colour/decoration choices are taking away the main focus from BioStar's primary value: user content.

I suggest the following changes to improve the layout of the BioStar pages:
- use the "Open Sans" web-font for cross-browser consistency (add to HTML header)
  `<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'>`
- tweak biostar.less.css as shown below:
  - use the web-font to ensure same rendering across platforms
  - make the "Sort by" dropdown list more prominent
  - highlight titles and user-text, but have a subdued colour for everything else
  - increase readability by having a larger line-height
  - subtle display of tags, which are important, but should not stand out
  - attention drawing top navigation bar is part of the page now, rather than governing it

``` css

@default-font-size:1em;

@navbar-color:#666;
@navbar-color-darker: darken(@navbar-color, 15%);

@title-size: large;
@title-color: red;
@bit: 18px;

.default-style {

}

body {
   .default-style;
   color: #666;
   background-color: white;
   line-height: 175%;
   font-family: 'Open Sans', 'Helvetica Neue', 'Helvetica', sans-serif;
}

p {
    color: #333;
}

.dropdown-toggle {
    border-style: solid;
    border-width: 1px;
    border-color: #08C;
}

.newpost {
    text-decoration: underline;
}

blockquote {

    padding: 0 0 0 15px;
    margin: 0 0 30px;
    border-left: 5px solid #EEE;

    p {
        margin-bottom: 0;
        font-size: 100%;
        font-weight: 200;
        line-height: 22.5px;
    }
}

.post-show {
    h1 { font-size:140% }
    h2 { font-size:130% }
    h3 { font-size:120% }
}

.badge-colors {
    .bronze { color: #CC9966; }
    .silver { color: #C0C0C0; }
    .gold   { color: #FFCC00; }
}    

code {
    border:0px solid white;

}

.add-comment {
    cursor: pointer;
}

.message {
    color:white;
    &:hover { text-decoration: underline; }
}

.navbar .brand {
    text-indent:8px;
    margin-left:0px;
    background-image: url(/static/img/g/star.png);
    background-repeat: no-repeat;
    background-position: 0px 4px;
}

.title {
    font-size:larger;
    margin-bottom:5px;
    color:#333333;
}

div .par {
    margin: 0px 0px 0.8em 0px;
    img {
        vertical-align: middle;
        border: 0;
    }
}

.postinfo {
      color: #858585;
      float: right;
}

#subheader{
    .title {
        text-align: center;
        font-size:larger;
    }
}

.peek {
    overflow: hidden;
    margin-bottom:5px;
}


.tag {
    font-size: small;
    margin: 2px 2px 2px 0;
    padding: 3px 6px 3px 6px;
    text-decoration: none;
    background-color: #ECECEC;
    color: #08C;
    &:hover{
        color:white;
        background-color:#666;
        text-decoration: none;
    }  
}

.post-type {
   margin-right: 8px;
   //color: #5F375E;
   background-color: #E0E0EC;
}

.tag-panel {
    .tag;
    float:left;
    padding: 5px 10px;
    margin:0px 20px 20px 20px;
    text-align:center;
    width:150px;
    font-size: larger;
    .tagname {
        font-weight: bold;
    }
    &:hover{
        a {
            color:white;
            text-decoration: none;
        }
        color:white;
        background-color:#6B3E4A;
    }
}

.tag-line {
    margin-bottom: 10px;
    line-height: 18px;
    float: left;
}

.mini-counts {
    font-size: 1.6em;
    font-weight: bold;
    height: 1.6ex;
    vertical-align: middle;
    text-align: center;
}

.status {  
  margin: 0 3px 0 0;
  padding: 5px;
  width: 4em;
  text-align: center;
}

#subheader {
    padding:0px;
    margin-bottom:0px;
}

.user-box{
    width:160px;
    height:160px;
    float:left;
    margin-bottom:10px;
    text-align:center;
}

input.search-query{
    width:auto;
}
.separator {
    border-bottom: 1px solid #DDD;
}

.hail {
    float:left;
    padding:3px;
    background-color:#efefef;
    border:1px solid #cccccc;
    margin:2px;
}

.comment {
    clear:left;
    .ajax-messages;

    .entry {
        padding:10px;
        margin-top:0.5em;
        color:#666666;
        background-color:#efefef;
        border-bottom: 1px solid #eeeeee;

    }
    .post-info-line{
        float: left;
        margin-right:10px;
        color:#666666;
    }
    .indent {
        margin-left:3em;  
    }
}

td {
    vertical-align:top;
    .title {
        text-shadow: 1px 2px 2px rgba(0, 0, 0, 0.1);
        font-size: 140%;
        font-weight: bold;
        padding-bottom: 2px;
        margin-bottom:10px;
        padding-top: 0px;
        color: #333;
    }

    .post-info-panel {
        width:10em;
        background-color:#EEEEEE;
        border: 1px solid #DDD;
        padding:1em;
        margin-left:0.5em;
        text-align:center;
    }

    p {
        .default-style;    
    }
}

#post-edit {
    background-color:#DDDDDD;
    padding:15px;
}
#footer {
    margin: 0 auto;
    margin-top:5px;
    border-top:1px solid #ddd;
    text-align: center;
    padding: 5px;
    img {
        vertical-align: middle;
        border: 0;
        border-image: initial;
    }
}
.post-table {
    vertical-align:top;
    padding:0px;
    width:100%;

    td {
        border-bottom: 1px solid #DDD;
        padding-top: 11px;
        padding-bottom: 11px;
    }

    .post-info-line{
        float: right;

        .relativetime{
            font-weight: bold;
            color: gray;
        }
        //margin-right:10px;
        //color:#666666;
    }
}

.unanswered {
    background-color: #8F2C47;
    color: white;
}

.answered {
    background-color: #75845C;
    color: #FFFFFF;
}

.forum {
    background-color: #B79538;
    color: #FFFFFF;
}

.tutorial {
    background-color: #2C7990;
    color: #FFFFFF;
}

.accepted {
    background-color: #75845C;
    color: #E1E818;
}

@vote-color:#EEEEEE;

.votes {
    background-color: @vote-color;
}

.post-title {
  font-size: larger;
  font-weight: bold;
  padding-bottom:0.5em;
  margin-bottom:5px;
  a {
    text-decoration: none;
    color: #333;
  }
}


#badge-list{
    td{
        padding: 5px;
        vertical-align: middle;
    }
    .multiplier{
        font-weight: bold;
        color: gray;
    }
}

.badge {
    .badge-colors;
    margin-left: 3px;
    .count  {
        color: #6D6D6D;
        padding-left: 1px;
    }
    .score {
        color: #444444;
        font-weight: bold;
        margin-right: 2px;
    }
}

.navbar-inner {
  padding-left: 20px;
  padding-right: 20px;
  background-color: red;
  background-image: -moz-linear-gradient(top, @navbar-color, @navbar-color-darker);
  background-image: -ms-linear-gradient(top, @navbar-color, @navbar-color-darker);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(@navbar-color), to(@navbar-color-darker));
  background-image: -webkit-linear-gradient(top, @navbar-color, @navbar-color-darker);
  background-image: -o-linear-gradient(top, @navbar-color, @navbar-color-darker);
  background-image: linear-gradient(top, @navbar-color, @navbar-color-darker);
  background-repeat: repeat-x;
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#333333', endColorstr='#222222', GradientType=0);
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
  -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25), inset 0 -1px 0 rgba(0, 0, 0, 0.1);
  -moz-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25), inset 0 -1px 0 rgba(0, 0, 0, 0.1);
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25), inset 0 -1px 0 rgba(0, 0, 0, 0.1);
  p a {
    color:white;
  }
  .nav > li > a {
    color: #dddddd;
  }
}

.page_bar {
    margin:0px auto 0px auto;
    margin-bottom:10px;
    text-align:center;
}

.page-bar-dropdown{
    float: right;
    .nav{
        margin-top: -8px;
        margin-bottom: 0px;
    }
}

.bookmark-list {
    .pagebar {
        background-color: #eeeeee;
        border-bottom:1px solid #ddd;
    }
    .bookmark {
        padding:5px;
        margin-bottom:2px;
        p {
            display:inline;
            font-size: @default-font-size;
        }
    }
}

.user-info {
    .ajax-messages;

    h2 { padding-bottom:5px; }
    .info-panel{ float:left; text-align:center;
    }
    .data-panel{ float:left;
        div { margin-bottom:5px; }
    }
    .bio-panel {
        p {
            .default-style;
            margin:0;
        }
    }
}
.badge-name {
    .badge-colors;
    background-color: #333;
    border: 1px solid #333;
    border-radius: 6px 6px 6px 6px;
    color: white !important;
    line-height: 1.9;
    margin: 0 3px 3px 0;
    padding: 4px 8px 4px 3px;
    text-decoration: none;
    border-image: initial;
}

.lastedit {
    font-size:smaller;
    margin-top:5px;
    font-style:italic;
}

.note-list {
    .pagebar {
        background-color: #eeeeee;
        border-bottom:1px solid #ddd;
    }
    .msg {
        padding:5px;
        margin-bottom:2px;
        p {
            display:inline;
            font-size: @default-font-size;
        }
    }
    .unread {
        font-weight:bold;
    }
}

.comment-delete {
    float:right;
    font-weight:bold;
    font-size:larger;
    &:hover {
        text-decoration: underline;
        cursor:pointer;
    }
}
.closed  { background-color: #F9F9F9;}
.deleted { opacity:0.75; border-right: 1px solid red;}
.suspended { h2 { color:red; }}

/* popup message rendering */

.ajax-messages {

    .vote-popover {
        position:absolute;
        margin-top:10px;
        color: black;
    }

    .error {
        background-color:#D7615F;
        padding:10px;
        border: 1px solid darken(#D7615F, 20%);
        opacity:0.9;
    }

    .success {
        background-color:#B6C2A1;
        padding:10px;
        border: 1px solid darken(#B6C2A1, 20%);
        opacity:0.9;
    }
}

.user-action {
    .ajax-messages;
    cursor:pointer;
}
.edit-action {
    .ajax-messages;
    cursor:pointer;
}

.mini-vote-box {
    .ajax-messages;

    padding:5px;
    margin-right:5px;
    width: 40px;
    height: 20px;
    float:left;

    .vote-up {
        width:20px;
        float:left;
        background-repeat: no-repeat;
        cursor:pointer;
    }
    .vote-count {
        width:15px;
        text-align:center;
        float:left;
    }
    .vote-up.vote-off { background-image: url("/static/img/g/glyphicons_213_up_arrow.png"); opacity:0.3; }
    .vote-up.vote-on  { background-image: url("/static/img/g/glyphicons_213_up_arrow.png"); }

    .vote-down.vote-off { background-image: url("/static/img/g/glyphicons_213_up_arrow.png"); opacity:0.3; }
    .vote-down.vote-on  { background-image: url("/static/img/g/glyphicons_213_up_arrow.png"); }
}

.vote-box{
    .ajax-messages;

    vertical-align: top;
    padding: 0px;

    .vote{

        text-align:center;
        width: 60px;
        float:left;
        margin:10px;

        .vote-count {

            font-size: 240%;
            font-weight: bold;
            text-align: center;
            margin:10px 0px 10px 0px;
        }

        .vote-up, .vote-accepted, .vote-bookmark, .vote-down {
            display: block;
            width: 44px;
            background-repeat: no-repeat;
            background-position: center;
            margin: auto;
            cursor:pointer;
            text-align: center;
        }

        .vote-bookmark {
            height:30px;
            background-position: center;
            margin-top:10px;
        }

        .vote-accepted {
            width: 44px;
            height:44px;
            background-position: center;
        }

        .vote-up.vote-off { background-image: url("/static/img/vote/vote-up-on.png"); opacity:0.3; &:hover { opacity:0.9; } }
        .vote-up.vote-on { background-image: url("/static/img/vote/vote-up-on.png"); }

        .vote-down.vote-off { background-image: url("/static/img/vote/vote-down-on.png"); opacity:0.3; &:hover { opacity:0.9; } }
        .vote-down.vote-on { background-image: url("/static/img/vote/vote-down-on.png"); }

        .vote-bookmark.vote-on  { background-image: url("/static/img/g/bookmark.png"); }
        .vote-bookmark.vote-off { background-image: url("/static/img/g/bookmark.png"); opacity:0.3; &:hover { opacity:0.9; } }
        .vote-accepted.vote-on  { background-image: url("/static/img/g/checkmark.png") }
        .vote-accepted.vote-off { background-image: url("/static/img/g/checkmark.png"); opacity:0.3; &:hover { opacity:0.9; }}
    }

}
```
